version: '3.8'

networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - laravel

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan" ]
    networks:
      - laravel

  npm:
    image: node:${NODE_VERSION}
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    networks:
      - laravel

  phpunit:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: phpunit
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "/var/www/html/vendor/bin/phpunit" ]
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: scheduler
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan", "schedule:work" ]
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      MYSQL_USER: ${PMA_USER}
      MYSQL_PASSWORD: ${PMA_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PMA_ROOT_PASSWORD}
      MAX_EXECUTION_TIME: ${PMA_MAX_EXECUTION_TIME}
      MEMORY_LIMIT: ${PMA_MEMORY_LIMIT}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
    depends_on:
      - mysql
    networks:
      - laravel


